version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.7.1-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: "luuvanduc/setchatbot:1"
    expose: ["5055"]